# Generated by Django 6.0.1 on 2026-03-23 11:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField(blank=True, default='')),
                ('excerpt', models.CharField(blank=True, default='', max_length=300)),
                ('event_date', models.DateField()),
                ('location', models.CharField(blank=True, default='', max_length=250)),
                ('cover_image', models.ImageField(blank=True, upload_to='photos/events/')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='photos/events/')),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('sort_order', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
