# Generated by Django 6.0.1 on 2026-03-23 11:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cert_number', models.CharField(blank=True, max_length=40, unique=True)),
                ('recipient_name', models.CharField(max_length=120)),
                ('cert_type', models.CharField(choices=[('appreciation', 'Appreciation'), ('participation', 'Participation'), ('leadership', 'Leadership'), ('welfare', 'Welfare'), ('custom', 'Custom')], default='appreciation', max_length=30)),
                ('body', models.TextField()),
                ('pdf_file', models.FileField(blank=True, upload_to='certificates/')),
                ('image_file', models.ImageField(blank=True, upload_to='certificates/')),
                ('verification_url', models.CharField(blank=True, default='', max_length=250)),
                ('qr_code', models.ImageField(blank=True, upload_to='certificates/')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
