# Generated by Django 6.0.1 on 2026-03-23 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0002_initial'),
        ('leaders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_certificates', to='leaders.leader'),
        ),
    ]
