# Generated by Django 6.0.1 on 2026-03-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('published', 'Published'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
    ]
