# Generated by Django 6.0.1 on 2026-03-23 11:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('chairman', 'Chairman'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('welfare', 'Welfare'), ('committee', 'Committee')], max_length=30)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('bio', models.TextField(blank=True, default='')),
                ('signature', models.ImageField(blank=True, upload_to='signatures/')),
                ('stamp', models.ImageField(blank=True, upload_to='signatures/')),
                ('is_active', models.BooleanField(default=True)),
                ('appointed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointees', to='leaders.leader')),
            ],
            options={
                'ordering': ['role', '-created_at'],
            },
        ),
    ]
