# Generated by Django 6.0.1 on 2026-03-27 06:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_verify_users', models.BooleanField(default=False)),
                ('can_export_users', models.BooleanField(default=False)),
                ('can_manage_memberships', models.BooleanField(default=False)),
                ('can_view_financials', models.BooleanField(default=False)),
                ('can_send_communications', models.BooleanField(default=False)),
                ('can_issue_certificates', models.BooleanField(default=False)),
                ('can_manage_events', models.BooleanField(default=False)),
                ('can_manage_leaders', models.BooleanField(default=False)),
                ('can_view_analytics', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='leaders.leader')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
