# Generated by Django 6.0.3 on 2026-03-28 01:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0003_leaderpermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='leader',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('role',), name='unique_active_leader_per_role'),
        ),
    ]
