# Generated by Django 6.0.3 on 2026-03-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='payment_screenshot',
            field=models.ImageField(blank=True, upload_to='payments/'),
        ),
        migrations.AddField(
            model_name='membership',
            name='payment_status',
            field=models.CharField(choices=[('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending_verification', max_length=30),
        ),
    ]
