# Generated by Django 6.0.1 on 2026-03-28 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_membership_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passport_number',
        ),
        migrations.AddField(
            model_name='membership',
            name='is_renewal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='previous_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='users.membership'),
        ),
        migrations.AddField(
            model_name='user',
            name='korean_phone',
            field=models.CharField(blank=True, default='', help_text='Korean phone number (e.g., 010-1234-5678)', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
    ]
