# Generated by Django 6.0.1 on 2026-03-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_renewal_fields_to_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='is_renewal',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='previous_membership',
        ),
        migrations.AddField(
            model_name='membership',
            name='last_renewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='renewal_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membership',
            name='renewal_history',
            field=models.JSONField(blank=True, default=list, help_text='List of {date, extended_from, extended_to, by}'),
        ),
    ]
