# Generated by Django 6.0.3 on 2026-03-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_membership_payment_screenshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
    ]
