# Generated by Django 6.0.1 on 2026-03-23 11:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(blank=True, max_length=40, unique=True)),
                ('subject', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('urgent', 'Urgent'), ('welfare', 'Welfare'), ('events', 'Events'), ('emergency', 'Emergency')], default='general', max_length=30)),
                ('audience', models.CharField(choices=[('all', 'All'), ('members_only', 'Members Only'), ('city', 'City'), ('category_group', 'Category Group')], default='all', max_length=30)),
                ('audience_filter', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('published', 'Published'), ('draft', 'Draft')], default='processing', max_length=20)),
                ('pdf_file', models.FileField(blank=True, upload_to='communications/')),
                ('image_file', models.ImageField(blank=True, upload_to='communications/')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
