# Generated by Django 6.0.1 on 2026-03-27 09:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_initial'),
        ('leaders', '0003_leaderpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('condolence', 'Condolence'), ('event', 'Upcoming Event'), ('welfare', 'Welfare'), ('notice', 'Notice'), ('celebration', 'Celebration')], default='general', max_length=30)),
                ('is_published', models.BooleanField(default=True)),
                ('cover_image', models.ImageField(blank=True, upload_to='announcements/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='leaders.leader')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
