# Generated by Django 6.0.3 on 2026-03-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('published', 'Published'), ('draft', 'Draft')], db_index=True, default='processing', max_length=20),
        ),
    ]
